TD_BASE = 'https://api.tdameritrade.com/v1/'
TD_ACCOUNTS = TD_BASE + 'accounts/'
TD_SEARCH = TD_BASE + 'instruments'
TD_INSTRUMENTS = TD_SEARCH + '/'
TD_QUOTES = TD_BASE + 'marketdata/quotes'
TD_HISTORY = TD_BASE + 'marketdata/%s/pricehistory'
TD_OPTIONCHAIN = TD_BASE + 'marketdata/chains'
TD_MOVERS = TD_BASE + 'marketdata/%s/movers'

ET_BASE = 'fake'