from opstrat import *

stratlist = [IronCondor,
             IronButterfly,
             #--------
             LongStraddle,
             ShortStrangle,
             LongStrangle,
             ShortStrangle,
             #--------
             LongCall,
             LongPut,
             ShortCall,
             ShortPut,
             #--------
             LongCallSpread,
             LongPutSpread,
             ShortCallSpread,
             ShortPutSpread,
             #--------
             BackCallSpread,
             BackPutSpread,
             #--------
             LongCallButterflySpread,
             LongPutButterflySpread,
             InverseCallButterfly,
             InversePutButterfly,
             #--------
             ChristmasTreeCallButterfly,
             FlipChristmasTreeCallButterfly,
             InvChristmasTreeCallButterfly,
             InvFlipChristmasTreeCallButterfly,
             #--------
             ChristmasTreePutButterfly,
             FlipChristmasTreePutButterfly,
             InvChristmasTreePutButterfly,
             InvFlipChristmasTreePutButterfly,
             #--------
             LongCallCondor,
             ShortCallCondor,
             LongPutCondor,
             ShortPutCondor             
]
